#!/bin/bash

#1 add repo
sudo add-apt-repository -y "deb http://172.22.238.229:9999 trusty main"
echo "====>DONE #1"

#2 update repo
sudo apt-get update
echo "====>DONE #2"

#3 install loanui
sudo apt-get install loanui -y
echo "====>DONE #3"

#3.5 update permission
chmod 755 /home/loanapp/loanui/start.sh
echo "====>DONE #3.5"

#4 install nvm
sudo curl https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
source ~/.profile
source ~/.bashrc
source ~/.nvm/nvm.sh


nvm --version

nvm install v6.2.2
npm install -g http-server

echo "=====>DONE #4"

#5 copy service file
sudo cp /home/loanapp/loanui/loanui.service /etc/systemd/system
echo "====>DONE #5"

sudo systemctl daemon-reload
sudo systemctl enable loanui.service

echo "====>DONE #5"

#6
sudo systemctl start loanui.service



echo "====>complete"

